---
title: "Measuring the car accidents rate by US state"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r include=FALSE}
# Course: 5210 Communicating Data
# Purpose: Illustrate unclear dash
# Author: Example project
# Date: 

```

```{r echo = FALSE}
# Clear environment of variables and functions
rm(list = ls(all = TRUE)) 

# Clear environmet of packages
if(is.null(sessionInfo()$otherPkgs) == FALSE)lapply(paste("package:", names(sessionInfo()$otherPkgs), sep=""), detach, character.only = TRUE, unload = TRUE)

```

```{r setup, include=FALSE}
# Load packages
library(flexdashboard)
library(ggplot2)
library(plotly)
library(dplyr)
library(openintro)
library(highcharter)
library(tidyverse)

```


```{r}
data <- read_csv("../02_raw_data/W7-4-2_bad_dash.csv")
```

```{r}
mycolors <- c("blue", "#FFC125", "darkgreen", "darkorange")
```

Interactive Data Visualization 
=====================================

Row
-------------------------------------

### Car accident Analysis

```{r}
valueBox(paste("Accident"),
         color = "warning")
```

### Total car accidents

```{r}
valueBox(length(data$STATE),
         icon = "fa-user")
```

### **Average labor cost**

```{r}
gauge(round(mean(data$LABORCOST),
            digits = 2),
            min = 0,
            max = 350,
            gaugeSectors(success = c(0, 150),
                         warning = c(150, 240),
                         danger = c(240, 350),
                         colors = c("green", "yellow", "red")))
```





### Texas

```{r}
valueBox(sum(data$STATE == "TX"),
         icon = 'fa-building')
```




### California

```{r}
valueBox(sum(data$STATE == "CA"),
         icon = 'fa-building')
```


### Florida

```{r}
valueBox(sum(data$STATE == "FL"),
         icon = 'fa-building')
```


### GEORGIA

```{r}
valueBox(sum(data$STATE == "GA"),
         icon = 'fa-building')
```

Row
-------------------------------

### TX has the most car accidents followed by CA

```{r}
p1 <- data %>%
         group_by(STATE) %>%
         summarise(count = n()) %>%
         plot_ly(x = ~STATE,
                 y = ~count,
                 color = "blue",
                 type = 'bar') %>%
layout(xaxis = list(title = "Accidents By STATE"),
yaxis = list(title = 'Count'))
p1
```

### Texas alone covers more than 36% of car accidents


```{r}
p2 <- data %>%
         group_by(STATE) %>%
         summarise(count = n()) %>%
         filter(count>50) %>%
         plot_ly(labels = ~STATE,
                 values = ~count,
                 marker = list(colors = mycolors)) %>%
         add_pie(hole = 0.2) %>%
         layout(xaxis = list(zeroline = F,
                             showline = F,
                             showticklabels = F,
                             showgrid = F),
                yaxis = list(zeroline = F,
                             showline = F,
                             showticklabels=F,
                             showgrid=F))
p2
```

### Average car accidentt happens in a 12th month of purchase
- which has 12k plus mileage

```{r}
p3 <- plot_ly(data,
              x = ~FM,
              y = ~MILEAGE,
              text = paste("FM:", data$FM,
                           "MILEAGE:",
                           data$MILEAGE),
              type = "bar") %>%
         layout(xaxis = list(title="FM"),
                yaxis = list(title = "Accident MILEAGE"))
p3
```

Row
------------------------------------
### maintenance cost Vs mileage

```{r}
p4 <- plot_ly(data, x=~MILEAGE) %>%
         add_markers(y = ~MAINTENANCE,
                     text = ~paste("MAINTENANCE: ", MAINTENANCE),
                     showlegend = F) %>%
         add_lines(y = ~fitted(loess(MAINTENANCE ~ FM)),
                   name = "Loess Smoother",
                   color = I("#FFC125"),
                   showlegend = T,
                   line = list(width=5)) %>%
         layout(xaxis = list(title = "MILEAGE"),
                yaxis = list(title = "MAINTENANCE ($)"))
p4
```

### Interactive map to show the accidents by state

```{r}
p5 <- data %>%
         group_by(STATE) %>%
         summarize(total = n())
p5$STATE <- abbr2state(p5$STATE)

highchart() %>%
         hc_title(text = "Car Accidents in US") %>%
         hc_subtitle(text = "Source: Accidents.csv") %>%
         hc_add_series_map(usgeojson, p5,
                           name = "State",
                           value = "total",
                           joinBy = c("woename", "STATE")) %>%
         hc_mapNavigation(enabled = T)
```


Column 
-----------------------------------

### Max Accident Month after a car is bought

```{r}
valueBox(max(data$FM),
         icon = "fa-user" )
```

### Average Labor cost
```{r}
valueBox(round(mean(data$LABORCOST),
               digits = 2),
         icon = "fa-area-chart")
```

### Average MILEAGE at Accident

```{r}
valueBox(round(mean(data$MILEAGE), digits = 2),
         icon = "fa-area-chart")
```





